# Generated by Django 4.1.2 on 2023-10-24 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_transaction',
            fields=[
                ('tr_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookquantity', models.PositiveIntegerField()),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('checkin_date', models.DateTimeField(blank=True, null=True)),
                ('total_days', models.PositiveIntegerField(blank=True, null=True)),
                ('perdayprice', models.BigIntegerField(blank=True)),
                ('totalPrice', models.PositiveIntegerField(blank=True, null=True)),
                ('grandtotalprice', models.BigIntegerField(blank=True, null=True)),
                ('stock', models.BigIntegerField(blank=True, null=True)),
                ('paymenttype', models.CharField(choices=[('cash', 'cash'), ('net-banking', 'net-banking'), ('UPI', 'UPI'), ('Card', 'Card')], default='cash', max_length=30, verbose_name='paymenttype')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='amsapp.bookstock2')),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='amsapp.bookstock2')),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
