# Generated by Django 4.1.2 on 2023-10-24 12:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0002_book_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_transaction',
            name='stock',
        ),
        migrations.AlterField(
            model_name='book_transaction',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amsapp.book2'),
        ),
        migrations.AlterField(
            model_name='book_transaction',
            name='checkout',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
